# Project configuration
project:
  name: "coremof_2019"  # Project name used for organizing data directories

# Database configuration
database:
  # Either specify an explicit path or let it auto-generate
  path: ${PROJECT_ROOT}/examples/data/${project.name}/raw
  # Only downloads if path doesn't exist or directory is empty
  remote_url: https://mof.tech.northwestern.edu/Datasets/CoREMOF%202019-mofdb-version:dc8a0295db.zip
  extract: true  # Whether to extract the downloaded file (if using remote_url)

# Output directory structure
output:
  base_dir: ${PROJECT_ROOT}/examples/data/${project.name}/  # Base directory for output

# Batch settings
batch:
  size: 5  # Number of structures per batch
  max_concurrent_jobs: 2  # Maximum number of concurrent jobs
  strategy: alphabetical  # Options: alphabetical, size_based, random
  # For size_based strategy, specify size thresholds
  size_thresholds: [1000, 5000, 10000]  # File sizes in bytes for batching

# Script paths - now referenced within the Python package
scripts:
  partial_charge: gRASPA_job_tracker.scripts.generate_partial_charge
  simulation: gRASPA_job_tracker.scripts.mps_run
  analysis: gRASPA_job_tracker.scripts.analyze_batch_output

# File templates
run_file_templates:
  simulation_input:  # This template gets these specific variables
    file_path: ${PROJECT_ROOT}/templates/simulation.input
    variables:
      NumberOfInitializationCycles: 2000
      NumberOfProductionCycles: 2000
      MoviesEvery: 3000000
  
#Forcefield files
forcefield_files:
  force_field_mixing_rules: ${PROJECT_ROOT}/forcefields/N2-Forcefield/force_field_mixing_rules.def
  force_field: ${PROJECT_ROOT}/forcefields/N2-Forcefield/force_field.def
  pseudo_atoms: ${PROJECT_ROOT}/forcefields/N2-Forcefield/pseudo_atoms.def
  CO2: ${PROJECT_ROOT}/forcefields/N2-Forcefield/CO2.def
  N2: ${PROJECT_ROOT}/forcefields/N2-Forcefield/N2.def

# SLURM configuration
slurm_config:
  account: bcvz-delta-gpu
  partition: gpuA100x4
  time: 2:00:00
  nodes: 1
  mem: 32GB

# Environment setup (optional)
environment_setup: |
  cd $SLURM_SUBMIT_DIR
  module load anaconda3_gpu
  source deactivate graspa
  export LD_LIBRARY_PATH=$HOME/software/gcc-13.3.0/lib64:$LD_LIBRARY_PATH
  source activate graspa
