# Project configuration
project:
  name: "coremof_clean"  # Project name used for organizing data directories

# Output directory structure
output:
  base_dir: ${PROJECT_ROOT}/examples/data/${project.name}/  # Base directory for output

# Database configuration
database:
  path: ${PROJECT_ROOT}/examples/data/${project.name}/raw
  # Only downloads if path doesn't exist or directory is empty
  remote_url: None
  extract: true  # Whether to extract the downloaded file (if using remote_url)



# Batch settings
batch:
  size: 20  # Number of structures per batch
  max_concurrent_jobs: 50  # Maximum number of concurrent jobs
  strategy: custom_alphabetical  # Options: alphabetical, custom_alphabetical, size_based, random
  # For size_based strategy, specify size thresholds
  size_thresholds: [1000, 5000, 10000]  # File sizes in bytes for batching
  copy_files: false  # Set to true if you want physical copies of files in batch directories

# Script paths - now referenced within the Python package
scripts:
  partial_charge: gRASPA_job_tracker.scripts.generate_partial_charge
  simulation: gRASPA_job_tracker.scripts.mps_run
  analysis: gRASPA_job_tracker.scripts.analyze_batch_output

# File templates
run_file_templates:
  simulation_input:  # This template gets these specific variables
    file_path: ${PROJECT_ROOT}/templates/simulation.input
    variables:
      NumberOfInitializationCycles: 2000000
      NumberOfProductionCycles: 2000000
      MoviesEvery: 3000000
  
#Forcefield files
forcefield_files:
  force_field_mixing_rules: ${PROJECT_ROOT}/forcefields/N2-Forcefield/force_field_mixing_rules.def
  force_field: ${PROJECT_ROOT}/forcefields/N2-Forcefield/force_field.def
  pseudo_atoms: ${PROJECT_ROOT}/forcefields/N2-Forcefield/pseudo_atoms.def
  CO2: ${PROJECT_ROOT}/forcefields/N2-Forcefield/CO2.def
  N2: ${PROJECT_ROOT}/forcefields/N2-Forcefield/N2.def

# SLURM configuration
slurm_config:
  account: bcvz-delta-gpu
  partition: gpuA100x4
  time: 5:00:00
  nodes: 1
  mem: 50GB

# Environment setup (optional)
environment_setup: |
  cd $SLURM_SUBMIT_DIR
  module load anaconda3_gpu
  source deactivate graspa
  export LD_LIBRARY_PATH=$HOME/software/gcc-13.3.0/lib64:$LD_LIBRARY_PATH
  export gRASPA_executable=$HOME/software/gRASPA/patch_Allegro/nvc_main.x
  source activate graspa
